### ISSUE TITLE
[v0.70] rapidyaml_archive.h compile fail

### ISSUE THREAD

**Issue by psallandre** [PavelKisliak/BitSerializer#3]
Hello, thanks for this nice library!

I was trying to update from 0.65 to 0.70 but this
```c++
cmake-build-preset-clang-18-debug/vcpkg_installed/x64-linux-c++20/include/bitserializer/rapidyaml_archive.h:596:16: error: no matching function for call to 'emitrs_yaml'
  596 |                                                                 *arg = ryml::emitrs_yaml<std::string>(mTree);
      |                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cmake-build-preset-clang-18-debug/vcpkg_installed/x64-linux-c++20/include/bitserializer/rapidyaml_archive.h:22:7: note: candidate function template not viable: requires 0 arguments, but 1 was provided
   22 |         void emitrs_yaml();
      |              ^
1 error generated.
```
Clang-18 Ubuntu 23.04
If I replace ryml::emitrs_yaml with ryml::emitrs then all is good.

I see that the CI is OK so I think it comes from c4 / ryml versions installed by vcpkg.
Looking at vcpkg/packages, I have c4core v0.1.9#1 and ryml v0.4.1#0
If I clean all vcpkg packages cache etc, it again installs thoses versions, not sure why vcpkg doesn't install latest versions of c4core and ryml...

**Comment by PavelKisliak** [comment]
Hello @psallandre ,

Thanks for the first issue :), I'm glad that you are interested my library.

About described error - I was tried to keep compatibility with old versions of Ryaml library, but looks like this doesn't work properly on your configuration (to be honest I've tested this only on Windows / VS2022). I can't check it right now with the described configuration. The CI is configured to test only with latest versions of third-party dependencies.

About issue with VCPKG, would be good to have more details how you are installing the library. If you are using a manifest file (vcpkg.json), the old version of `RYML` library might be installed due to old "builtin-baseline". You can try to update the baseline to latest (but this will update all your dependencies), or try to override only `RYML`:
```json
{
  "dependencies": [ ... ],
  "builtin-baseline": "Your baseline hash",
  "overrides": [
    {
      "name": "ryml",
      "version": "0.5.0"
    }
  ]
}
```

**Comment by psallandre** [comment]
Indeed, upgrading `builtin-baseline` did the trick.
I run `vcpkg x-update-baseline --add-initial-baseline`, and now it compiles OK
Thanks
